-- Parti2 Bet Module - Knockout Stage Generator (48-team format)
-- Version: 2.0
-- Date: 2026-05-27
-- Description: Template + SQL placeholders for Round of 32 (48 teams)

-- =============================================================================
-- KNOCKOUT STAGE STRUCTURE (48 TEAMS - OFFICIAL FIFA 2026 SEEDING)
-- =============================================================================
-- Round of 32: 16 matches (32 teams → 16 winners)
--   - 12 group winners (1st place teams from groups A-L)
--   - 12 group runners-up (2nd place teams from groups A-L)
--   - 8 best third-place finishers (3rd place teams ranked by performance)
--
-- Round of 16: 8 matches (16 winners → 8 winners)
-- Quarterfinals: 4 matches (8 winners → 4 winners)
-- Semifinals: 2 matches (4 winners → 2 winners)
-- Third Place: 1 match (for 3rd place position)
-- Final: 1 match (championship)
-- Total Knockout Matches: 32

-- =============================================================================
-- ROUND OF 32 SEEDING (16 matches, 32 teams)
-- =============================================================================
-- Official FIFA 2026 bracket structure for 12 groups:
-- Match 1: 1st A vs Best 3rd / 2nd X
-- Match 2: 1st C vs 2nd D
-- Match 3: 1st B vs 2nd A
-- Match 4: 1st D vs 2nd C
-- Match 5: 1st E vs Best 3rd / 2nd X
-- Match 6: 1st G vs 2nd F
-- Match 7: 1st F vs 2nd E
-- Match 8: 1st H vs 2nd G
-- Match 9: 1st I vs Best 3rd / 2nd X
-- Match 10: 1st K vs 2nd J
-- Match 11: 1st J vs 2nd I
-- Match 12: 1st L vs 2nd K
-- Match 13: 1st L vs Best 3rd / 2nd X  (if 1st L not already played)
-- Match 14: 1st B vs 2nd I (alternative)
-- Match 15: 1st D vs 2nd A (alternative)
-- Match 16: 1st H vs 2nd K (alternative)

-- =============================================================================
-- TEMPLATE: KNOCKOUT BRACKET CREATION
-- =============================================================================
-- To be executed after group stage is complete:
-- 1. Run group stage results (matches with home_score_official, away_score_official)
-- 2. Calculate group standings
-- 3. Identify:
--    - 12 group winners (1st place from A-L)
--    - 12 group runners-up (2nd place from A-L)
--    - Best 8 third-place finishers (top 3rd place teams)
-- 4. Create 16 Round of 32 matches with known team IDs
-- 5. Create 32 total knockout matches with NULL team IDs (filled dynamically)

-- =============================================================================
-- PLACEHOLDER SQL (to be customized with actual group results)
-- =============================================================================

-- This is a prepared statement structure:
-- After group stage completion, execute:
--
-- INSERT INTO bet_matches (tournament_id, stage, group_name, kickoff_at, home_team_id, away_team_id, status)
-- SELECT
--   :tournament_id,
--   'round_of_32'::bet_match_stage,
--   'RO16-' || row_number() OVER (ORDER BY ko.match_seq),
--   ko.kickoff_at,
--   ko.home_team_id,
--   ko.away_team_id,
--   'scheduled'::bet_match_status
-- FROM (
--   SELECT 1 as match_seq, 
--     (SELECT id FROM bet_teams WHERE fifa_code = 'MEX') as home_team_id,
--     (SELECT id FROM qualified_third_place_teams LIMIT 1) as away_team_id,
--     '2026-07-03 14:00:00+00'::TIMESTAMP as kickoff_at
--   UNION ALL
--   SELECT 2, 
--     (SELECT id FROM bet_teams WHERE fifa_code = 'BRA'), 
--     (SELECT id FROM bet_teams WHERE fifa_code = 'URU'),
--     '2026-07-03 17:00:00+00'::TIMESTAMP
--   -- ... 14 more rows
-- ) ko;

-- =============================================================================
-- QUARTERFINALS TEMPLATE (8 matches)
-- =============================================================================
-- Winners of RO16 matches 1 vs 2 → QF Match 1
-- Winners of RO16 matches 3 vs 4 → QF Match 2
-- Winners of RO16 matches 5 vs 6 → QF Match 3
-- Winners of RO16 matches 7 vs 8 → QF Match 4
-- Winners of RO16 matches 9 vs 10 → QF Match 5
-- Winners of RO16 matches 11 vs 12 → QF Match 6
-- Winners of RO16 matches 13 vs 14 → QF Match 7
-- Winners of RO16 matches 15 vs 16 → QF Match 8

-- =============================================================================
-- SEMIFINALS TEMPLATE (4 matches)
-- =============================================================================
-- QF Winners 1 vs 2 → SF Match 1
-- QF Winners 3 vs 4 → SF Match 2
-- QF Winners 5 vs 6 → SF Match 3
-- QF Winners 7 vs 8 → SF Match 4

-- =============================================================================
-- THIRD PLACE & FINAL TEMPLATE (2 matches)
-- =============================================================================
-- Third Place: SF Loser 1 vs SF Loser 2
-- Final: SF Winner 1 vs SF Winner 2

-- =============================================================================
-- NOTES
-- =============================================================================
-- - Team IDs are determined dynamically based on group standings
-- - All matches initially created in 'scheduled' status
-- - Kickoff dates: RO16 (July 3-4), QF (July 5-6), SF (July 9-10), Final (July 14)
-- - Third Place match typically scheduled 2 days before final (July 12)
-- - This requires post-processing after group stage completion

